### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by malys** [timxx/kdiff3#1]
Nice job.
Please could you provide release files  for Windows?

Thx

**Comment by chillitom** [comment]
👍 please!

Any plans to try and get these changes merged upstream?

**Comment by timxx** [comment]
@malys Sorry, I'm using Linux OS.

**Comment by malys** [comment]
@timxx No problem for that.
It's possible to associate artifact (binaries, setup) to https://ci.appveyor.com/project/timxx/kdiff3/branch/master/job/e3qrgq88f18chwy6/artifacts

**Comment by timxx** [comment]
@malys You can find the package from [here (32bit)](https://ci.appveyor.com/project/timxx/kdiff3/build/job/booidffpkylsy8qo/artifacts) and [here (64bit)](https://ci.appveyor.com/project/timxx/kdiff3/build/job/j6o5fa3swnp5jlqr/artifacts) now :)

**Comment by malys** [comment]
@timxx  Thx a lot.

**Comment by chintan9** [comment]
@timxx  Unable to access packages.
